### ISSUE TITLE
Docker config.production.json

### ISSUE THREAD

**Issue by eugeneromancenko** [elijahsgh/terraform-gke-ghost#1]
Hi.

Trying to build Doker image, but looks like config.production.json file missing from repo.  What is this file for ?

**Comment by abdulsalamk** [comment]
I have added all variables into a "terraform.tfvars" file, but it is not picking it up. Any idea why this could be? Here is the contents of the file ..

`db_instance          = "< MY DB INSTANCE>"
  db_password          = "< MY DB PASSWORD>"
  db_ip                = "< MY DB IP>"
  zone                 = "europe-west2"
  region               = "europe-west2-a"
  project              = "<MY PROJECT>"
  prefix               = "ghost"
  mail_password        = "<MAIL PASSWORD>"
  ghostimage           = "ghost:latest"
  backend_service_name = "<BACKEND>"

  ghost_envvars = {
  url              = "https://<YOUR URL>"
  server__host     = "0.0.0.0"
  server__port     = "2368"
  NODE_ENV         = "production"
  logging__level   = "info"
  database__client = "mysql"

  mail__transport                 = "SMTP"
  mail__options__service          = "<YOUR SERVICE>"
  mail__options__host             = "<YOUR SMTP HOST>"
  mail__options__port             = "<YOUR SMTP PORT>"
  mail__options__auth__user       = "<YOUR SMTP USER>"
  mail__options__secureConnection = "<SET TO TRUE OR OMIT IF NOT USING 465>"
  storage__active                 = "gcloud"
  storage__gcloud__projectId      = "<YOUR GCP PROJECT>"
  storage__gcloud__assetDomain    = "<YOUR ASSET DOMAIN - LEAVE TRAILING SLASH>/"
  storage__gcloud__insecure       = false
  storage__gcloud__maxAge         = 3600
  storage__gcloud__key            = "/var/run/secrets/bucket/key.json"
}`

**Comment by elijahsgh** [comment]
> Hi.
> 
> Trying to build Doker image, but looks like config.production.json file missing from repo. What is this file for ?

Hi. Config.production.json is the Ghost CMS production settings.
You can read about it here: https://ghost.org/docs/config/

**Comment by elijahsgh** [comment]
> I have added all variables into a "terraform.tfvars" file, but it is not picking it up. Any idea why this could be?

This is a standard terraform module. It's meant to be used as a module. Are you cloning this repo and then using "terraform apply" with the terraform.tfvars above? It should still work like that.

Please open a new issue for this. This issue was about config.production.json

**Comment by elijahsgh** [comment]
Config.production.json is the Ghost CMS production settings.
You can read about it here: https://ghost.org/docs/config/
